# Generated by Django 5.2.14 on 2026-06-09 14:41

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = []

    operations: ClassVar[list[migrations.CreateModel]] = [
        migrations.CreateModel(
            name="EDRWebPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=255, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField()),
                ("appointments", models.JSONField(default=list)),
                ("payload", models.JSONField(default=dict)),
            ],
        ),
    ]
