# Generated by Django 5.2.14 on 2026-06-10 07:49

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("edrweb", "0001_initial"),
    ]

    operations: ClassVar[list[migrations.AddField]] = [
        migrations.AddField(
            model_name="edrwebpatient",
            name="feed_removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edrwebpatient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
