# Generated by Django 5.2.14 on 2026-06-10 09:16

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("edrweb", "0002_edrwebpatient_feed_removed_at_and_more"),
    ]

    operations: ClassVar[list[migrations.AlterField]] = [
        migrations.AlterField(
            model_name="edrwebpatient",
            name="appointments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Current EDRWeb Appointments array for reminder messaging. "
                    "Each item must include AppointmentDate as YYYY-MM-DD and "
                    "may include Facility with FacilityName, Latitude, and "
                    "Longitude. Example: "
                    '[{"AppointmentDate": "2026-06-20", "Facility": '
                    '{"FacilityName": "WC BLUE DOWNS CLINIC", "Latitude": '
                    '-33.9744, "Longitude": 18.7032}}].'
                ),
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="feed_removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Bifrost processing time when this EDRWeb Patient was "
                    "marked absent from the full feed. Django admin manages "
                    "this field from is_active: deactivating sets it, "
                    "reactivating clears it."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether this EDRWeb Patient is currently present in the "
                    "EDRWeb Appointment Reminder Feed. Inactive records should "
                    "not drive active EDRWeb reminder messaging."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="patient_id",
            field=models.CharField(
                help_text=(
                    "Stable EDRWeb PersonId for this EDRWeb Patient. Used as "
                    "the local upsert key for EDRWeb appointment reminder "
                    "snapshots; not shared with SyNCH patient identifiers."
                ),
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text=(
                    "Residual upstream EDRWeb fields not promoted into "
                    "explicit model columns. Kept for inspection and "
                    "troubleshooting; read-only in admin."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text=(
                    "WhatsApp phone number from EDRWeb PhoneNumber, usually in "
                    "E.164 format. Blank means EDRWeb did not provide a phone "
                    "number; future Turn sync cannot send reminders without one."
                ),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="updated_at",
            field=models.DateTimeField(
                help_text=(
                    "EDRWeb UpdatedAt timestamp for this snapshot. Bifrost "
                    "uses the latest stored value as the next delta checkpoint, "
                    "so do not set it in the future."
                )
            ),
        ),
    ]
