# Generated by Django 5.2.14 on 2026-06-10 14:00

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("edrweb", "0003_alter_edrwebpatient_appointments_and_more"),
    ]

    operations: ClassVar[list[migrations.AddField]] = [
        migrations.AddField(
            model_name="edrwebpatient",
            name="messaging_contact_activated",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether Turn has accepted the EDRWeb welcome-message "
                    "activation trigger for the current active EDRWeb "
                    "messaging phone number."
                ),
            ),
        ),
    ]
