# Generated by Django 5.2.14 on 2026-06-10 14:45

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("edrweb", "0004_edrwebpatient_messaging_contact_activated"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.AddField(
            model_name="edrwebpatient",
            name="active_messaging_phone_number",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Normalized WhatsApp phone number for the Turn contact "
                    "Bifrost last activated for this EDRWeb Patient. Blank "
                    "means no EDRWeb messaging contact activation has "
                    "completed yet."
                ),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="edrwebpatient",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Stored WhatsApp phone number from EDRWeb PhoneNumber, "
                    "normalized to E.164. Blank means EDRWeb did not provide a "
                    "usable phone number; future Turn sync cannot send reminders "
                    "without one."
                ),
                max_length=255,
            ),
        ),
    ]
