# Generated by Django 5.2.13 on 2026-04-20 12:33

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = []

    operations: ClassVar[list[migrations.CreateModel]] = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ccmdd_patient_id", models.CharField(max_length=255, unique=True)),
                ("date_created", models.DateTimeField()),
                ("date_updated", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
            ],
        ),
    ]
