# Generated by Django 5.2.13 on 2026-04-20 14:58

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0001_initial"),
    ]

    operations: ClassVar[list[migrations.CreateModel]] = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ccmdd_prescription_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("date_created", models.DateTimeField()),
                ("date_updated", models.DateTimeField()),
                ("facility_id", models.IntegerField(blank=True, null=True)),
                ("patient_id", models.CharField(max_length=255)),
                ("patient_phone", models.CharField(blank=True, max_length=255)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("return_dates", models.JSONField(default=list)),
                ("payload", models.JSONField(default=dict)),
            ],
        ),
    ]
