# Generated by Django 5.2.13 on 2026-04-21 13:43

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0002_prescription"),
    ]

    operations: ClassVar[list[migrations.CreateModel]] = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ccmdd_facility_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.CharField(blank=True, max_length=255)),
                ("longitude", models.CharField(blank=True, max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=255)),
                ("address_1", models.CharField(blank=True, max_length=255)),
                ("address_2", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(default=dict)),
            ],
        ),
    ]
