# Generated by Django 5.2.13 on 2026-04-28 09:53
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0003_facility"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "facilities"},
        ),
        migrations.AddField(
            model_name="patient",
            name="invite_sent",
            field=models.BooleanField(default=False),
        ),
    ]
