# Generated by Django 5.2.13 on 2026-04-28 10:01

from typing import ClassVar

from django.db import migrations


def existing_users_invite_sent(apps, scheme_editor):
    Patient = apps.get_model("synch", "Patient")
    Patient.objects.update(invite_sent=True)


def noop(apps, scheme_editor):
    return


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0004_alter_facility_options_patient_invite_sent"),
    ]

    operations: ClassVar[list[migrations.operations.base.Operation]] = [
        migrations.RunPython(existing_users_invite_sent, noop),
    ]
