# ruff: noqa: RUF012
# Generated by Django 5.2.14 on 2026-05-19 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("synch", "0005_invite_sent_existing_patients"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUser",
            fields=[],
            options={
                "verbose_name": "API user",
                "verbose_name_plural": "API users",
                "proxy": True,
                "permissions": (("send_otp", "Can send OTP delivery requests"),),
            },
            bases=("auth.user",),
        ),
    ]
