# ruff: noqa: RUF012
# Generated by Django 5.2.14 on 2026-05-18 15:28

from io import StringIO

from django.core.management import call_command
from django.db import migrations


def create_otp_delivery_throttle_cache_table(apps, schema_editor) -> None:
    existing_tables = schema_editor.connection.introspection.table_names()
    if "otp_delivery_throttle_cache" in existing_tables:
        return

    call_command(
        "createcachetable",
        "otp_delivery_throttle_cache",
        database=schema_editor.connection.alias,
        verbosity=0,
        stdout=StringIO(),
        stderr=StringIO(),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("synch", "0006_api_user_permission"),
    ]

    operations = [
        migrations.RunPython(
            create_otp_delivery_throttle_cache_table,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
