# Generated by Django 5.2.14 on 2026-06-02 09:43

from typing import ClassVar

import phonenumbers
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


def _normalize_phone_number(value: str) -> str | None:
    try:
        phone_number = phonenumbers.parse(value, "ZA")
    except phonenumbers.NumberParseException:
        return None

    return phonenumbers.format_number(
        phone_number,
        phonenumbers.PhoneNumberFormat.E164,
    )


def backfill_active_messaging_phone_number(apps, schema_editor) -> None:
    Patient = apps.get_model("synch", "Patient")
    Prescription = apps.get_model("synch", "Prescription")

    patients_to_update = []
    for patient in Patient.objects.filter(invite_sent=True).iterator():
        prescriptions = Prescription.objects.filter(
            patient_id=patient.ccmdd_patient_id
        ).order_by("-date_created", "-pk")

        for prescription in prescriptions:
            normalized_phone_number = _normalize_phone_number(
                prescription.patient_phone
            )
            if normalized_phone_number is None:
                continue

            patient.active_messaging_phone_number = normalized_phone_number
            patients_to_update.append(patient)
            break

    if patients_to_update:
        Patient.objects.bulk_update(
            patients_to_update,
            ["active_messaging_phone_number"],
        )


def noop(apps, schema_editor) -> None:
    return


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0007_create_otp_delivery_throttle_cache"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AddField(
            model_name="patient",
            name="active_messaging_phone_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_active_messaging_phone_number, noop),
    ]
