# Generated by Django 5.2.15 on 2026-07-15 10:38

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0008_patient_active_messaging_phone_number"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_facility_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_facility_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_facility_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_next_appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_patient_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
