# Generated by Django 5.2.15 on 2026-09-23 14:33

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0009_patient_turn_appointment_context_facility_latitude_and_more"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.AddField(
            model_name="patient",
            name="turn_appointment_context_appointment_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="version",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
