# Generated by Django 5.2.15 on 2026-09-23 14:36

from typing import ClassVar

from django.db import migrations


def backfill_prescription_version(apps, schema_editor) -> None:
    Prescription = apps.get_model("synch", "Prescription")
    prescriptions_to_update = []

    for prescription in Prescription.objects.all().iterator():
        if not isinstance(prescription.payload, dict):
            continue

        payload = prescription.payload.copy()
        if "version" not in payload:
            continue

        version = payload["version"]
        if (
            version is not None
            and version != ""
            and (not isinstance(version, int) or isinstance(version, bool))
        ):
            continue

        prescription.version = None if version in (None, "") else version
        payload.pop("version")
        prescription.payload = payload
        prescriptions_to_update.append(prescription)

    if prescriptions_to_update:
        Prescription.objects.bulk_update(
            prescriptions_to_update,
            ["version", "payload"],
        )


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("synch", "0010_patient_turn_appointment_context_appointment_type_and_more"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.RunPython(backfill_prescription_version, migrations.RunPython.noop),
    ]
